// <auto-generated />
namespace Motonet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PhotoLastModified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhotoLastModified));
        
        string IMigrationMetadata.Id
        {
            get { return "201509241302256_PhotoLastModified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
